class CTT(Tk):
    def __init__(self, theme : str): ...
    def titlebarconfig(self, color : dict, height: int): ...
    def title(self, text : int): ...
    def title_grey(self): ...
    def title_back(self): ...
    def usetitle(self, flag : bool): ...
    def titlenameconfig(self, pack : str, font : tuple): ...
    def useicon(self, flag : bool): ...
    def popupmenu(self, event : any): ...
    def iconphoto(self, image : str): ...
    def iconbitmap(self, image : str): ...
    def exit_on_enter(self, event : any): ...
    def exit_on_leave(self, event : any): ...
    def exit_grey(self, event : any): ...
    def exit_back(self, event : any): ...
    def min_on_enter(self, event : any): ...
    def min_on_leave(self, event : any): ...
    def min_grey(self, event : any): ...
    def min_back(self, event : any): ...
    def max_on_enter(self, event : any): ...
    def max_on_leave(self, event : any): ...
    def max_grey(self, event : any): ...
    def max_back(self, event : any): ...
    def disabledo(self): ...
    def usemaxmin(self, minsize : bool, maxsize : bool, minshow : bool, maxshow : bool): ...
    def setup(self): ...
    def moving(self, event : any): ...
    def dragging(self, event : any): ...
    def maxsize(self, event : any): ...
    def resize(self): ...
    def minsize(self): ...
    def deminsize(self, event : any): ...
    def focusout(self, event : any): ...
    def focusin(self, event : any): ...
    def useblur(self, acrylic : bool, dark : bool): ...
    def close(self, evnet : any): ...
    def sg(self, w : int, h : int): ...
    def geometry(self, size : str): ...
    def settheme(self, theme : str): ...
